#!/usr/bin/ruby
#
# Copyright 2012 Nextdoor.com, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This is a bit of example code useful for testing the Thycotic module
# itself, without worying about the Puppet integration.
# 
# Example usage:
#   (first, change the secretid and secretname below)
#
#   ruby test.rb
#

require File.join(File.dirname(__FILE__), 'thycotic.rb')
require File.join(File.dirname(__FILE__), 'parseconfig.rb')

secretid = '<insert secretid here>'
secretname = '<insert secret name here>'

# Get our auth options from the config file, or fail.
config = ParseConfig.new('/etc/puppet/thycotic.conf')

thycotic = Thycotic.new(config.get_value('url'), config.get_value('user'), config.get_value('password'), config.get_value('orgcode'), true)
secret = thycotic.getSecret(secretid)

print "Secret Data:\n"
print secret.to_yaml

